#!/usr/bin/env bash

REMOTE_USER=
GIT_EMAIL=
GIT_USERNAME=
TEAMMATE_GITHUB_ACCOUNTS=()
# SERVERS=("s1" "s2" "s3")
SERVERS=()

SERVICE_NAME=
REPO_DIR=
MYSQL_USER=root
MYSQL_PASSWORD=root
NGINX_ACCESS_LOG=/var/log/nginx/access.log
MYSQL_SLOW_LOG=/var/log/mysql/slow.log
SQLITE_TRACE_LOG=
STATS_DIR=
